version: '3.8'

services:
    postgresql:
        image: postgres:16
        environment:
            POSTGRES_DB: tennis_aeor
            POSTGRES_USER: dhia
            POSTGRES_PASSWORD: 7BxD3pxUU00LeYhhqzb2h2xw1o0jDfq2
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
